
import { CAPAStatus, CAPAPriority, CAPASource, CAPAEffectivenessRating } from '@/types/enums';

export { CAPAStatus, CAPAPriority, CAPASource, CAPAEffectivenessRating };

export interface CAPA {
  id: string;
  title: string;
  description: string;
  status: CAPAStatus;
  priority: CAPAPriority;
  source: CAPASource;
  created_at: string;
  updated_at: string;
  due_date: string;
  completion_date?: string;
  verification_date?: string;
  assigned_to: string;
  created_by: string;
  root_cause?: string;
  corrective_action?: string;
  preventive_action?: string;
  effectiveness_criteria?: string;
  effectiveness_rating?: CAPAEffectivenessRating;
  effectiveness_verified?: boolean;
  department?: string;
  verification_method?: string;
  verified_by?: string;
  source_id?: string;
  fsma204_compliant?: boolean;
}

export interface CAPAFilter {
  status?: CAPAStatus | CAPAStatus[];
  priority?: CAPAPriority | CAPAPriority[];
  source?: CAPASource | CAPASource[];
  department?: string | string[];
  searchTerm?: string;
  dateRange?: {
    start: string;
    end: string;
  };
}

export interface CAPAActivity {
  id: string;
  capa_id: string;
  performed_at: string;
  old_status?: CAPAStatus;
  new_status?: CAPAStatus;
  action_type: string;
  action_description: string;
  performed_by: string;
  metadata?: Record<string, any>;
}

export interface CAPAStats {
  total: number;
  open: number;
  inProgress: number;
  completed: number;
  overdue: number;
  byPriority: Record<CAPAPriority, number>;
  bySource: Record<CAPASource, number>;
  byDepartment: Record<string, number>;
  recentActivities: CAPAActivity[];
}

export interface CAPAListProps {
  items: CAPA[];  // Changed from 'capas' to 'items' to match implementation
  loading: boolean;
  error: string | null;
  onCAPAClick: (capa: CAPA) => void;
}

export interface CreateCAPADialogProps {
  open: boolean;  // Changed from 'isOpen' to 'open' to match implementation
  onClose: () => void;
  onSubmit: (capaData: any) => void;
}

export interface AutoGeneratedCAPAProps {
  sourceData: any;
  onAccept: () => void;
  onReject: () => void;
}
