-- Fix the RLS security issues by enabling RLS on all tables that have policies
-- This will address the "Policy Exists RLS Disabled" errors

-- Enable RLS on tables with policies but RLS disabled
ALTER TABLE IF EXISTS public.audit_findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.audits ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.capa_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.capa_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.capa_effectiveness_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.capa_related_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.capa_related_training ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.capa_workflow_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ccps ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.components ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_category_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_editor_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_permission_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_previews ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_status_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_workflow_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.employee_certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.facility_standards ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.haccp_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kpi_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kpi_production_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kpi_quality_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kpi_safety_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.module_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.nc_activities ENABLE ROW LEVEL SECURITY;