
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vngmjjvfofoggfqgpizo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZ21qanZmb2ZvZ2dmcWdwaXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Nzk1NjYsImV4cCI6MjA1ODQ1NTU2Nn0.hKuiNWB9g90lklzXollw-O7-8kHCl33wKYmC5EW_sLI";

// Use a global variable to ensure true singleton behavior
declare global {
  var __supabase: ReturnType<typeof createClient<Database>> | undefined;
}

function createSupabaseClient() {
  // Check if we already have a global instance
  if (globalThis.__supabase) {
    return globalThis.__supabase;
  }

  // Create new instance and store it globally
  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  });

  // Store globally to prevent multiple instances
  globalThis.__supabase = client;
  return client;
}

export const supabase = createSupabaseClient();

// Export auth helpers
export { authHelpers } from './authHelpers';
